### ISSUE TITLE
Checklist for v1.0

### ISSUE THREAD

**Issue by damcclean** [ThunderbirdSSG/Thunderbird#13]
List of things to be implemented before v1.0 release of Thunderbird.

- [X] Frontend Implementation
- [x] Fix Thunderbird asset copying stuff for Windows #11 
- [x] Fix blade implementation of the content (currently broken)
- [x] Ngnix rewrite rules #5 
- [x] Make a Thunderbird landing page
- [x] Tidy up the code base into different files to help organise stuff #4

**Comment by damcclean** [comment]
Looks like we're nearly good to go for v1 release!
